title: Quran
description: >
  هذا القسم مخصص للقرآن الكريم.
theme: jekyll-theme-minimal
enabled: true
url: "https://example.com"
baseurl: "/quran"
repository: "readhash/readhash.github.io"
branch: "main"
